### ISSUE TITLE
Sass: Installation Tutorial for Windows Users

### ISSUE THREAD

**Issue by ricardozea** [derek-skinner/Inflame#1]
Not an issue per-se, but I noticed that there's a link to a Sass tutorial in the [CSS section of the Readme](https://github.com/derek-skinner/Inflame#css). However, in that tutorial there's no mention of how to install Sass so beginners may be lost.

I wrote a tutorial on Medium.com called [[Sass] For Beginners: The Friendliest Guide About INSTALLING and USING Sass on Windows](https://medium.com/@ricardozea/sass-for-beginners-the-friendliest-guide-about-how-to-install-use-sass-on-windows-22ff4a32c1f7) that if you want you can add to your CSS section in the Readme.

If you do add it, huge Thanks! If not, no worries :)

**Comment by derek-skinner** [comment]
Very nice! I'll add it and put you in the credits section. Thanks!
